### ISSUE TITLE
Cannot launch travis module

### ISSUE THREAD

**Issue by c0rv4x** [pownjs/pown-travis#2]
Hey, I have installed pownjs as it was shown in the original manual, then I have installed the travis module like this 
`pown modules install travis`

I can see the module in the list of installed modules, but cannot launch it. I keep seing empty output for 
`pown travis dump github`

Looks like the module could not be found or something similar

<img width="895" alt="Screenshot 2020-07-07 at 20 10 26" src="https://user-images.githubusercontent.com/7037785/86817621-edc12000-c08d-11ea-9f10-5299e55f781b.png">

Could you tell me what I am doing wrong?

**Comment by pdparchitect** [comment]
Try `pown module install @pown/travis`.

**Comment by c0rv4x** [comment]
Oh yeah, this helped. Thank you, @pdparchitect
